### ISSUE TITLE
[bug]: error postgres parser in test mode

### ISSUE THREAD

**Issue by 0xVikasRushi** [keploy/keploy#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Bug Description**

While testing an [API](https://github.com/0xVikasRushi/samples-typescript/tree/main/postgres-typeorm) developed with Node.js (TypeScript) and PostgreSQL, I encountered the following error message in **test mode:**

![Error Screenshot](https://github.com/keploy/keploy/assets/88543171/d45083c9-4ae3-407a-97fb-1726b8edf046)

Additionally, I've attached the debug logs for further analysis: [logs.txt](https://github.com/keploy/keploy/files/13066793/logs.txt).

**Environment**

- Operating System: macOS arm64
- Container Environment: colima
- keploy Version: 2.0.0-alpha35

### Steps to reproduce

1. clone repo sample postgres [repo](https://github.com/0xVikasRushi/samples-typescript/tree/main/postgres-typeorm)
2. `colima start`
3. add alias for keploy 
4. `docker network create keploy-network`
5. `docker compose up -d`
6. `docker build -t postgres-app:1.0 .`
7. `keploy record -c "docker run -p 3000:3000 --name postgresTypeormApp --network keploy-network postgres-app:1.0"`
8. use curl or postman send some requests
9. `keploy test -c "docker run -p 3000:3000 --name postgresTypeormApp --network keploy-network postgres-app:1.0" --delay 10`

### Environment

Release

### Version

Local

### Repository

keploy

**Comment by EraKin575** [comment]
I would like to take up this issue

**Comment by Sarthak160** [comment]
> I would like to take up this issue

Hi @EraKin575 , Since this issue requires well understood knowledge of Postgres protocol and How Keploy has been using postgres parsers for capturing tcp buffer between client and server , in readable yaml mocks. So this can be a bit complex task for you . But If you still wanna give it a try, can start by replicating the same problem in your local . 
As per my research , node postgres clients make some authentication calls randomly which can be mismatched in record and test . But If we got to know which packets are causing this heart beat kind of situation a particular connection thread we can add a condition for directly returning them instead of removing them while retrieving from mocks .

**Comment by gouravkrosx** [comment]
@Sarthak160 , Is this issue still relevant?

**Comment by Sarthak160** [comment]
Now we support node clients for postgres. I dont think user will face this issue now.
