### ISSUE TITLE
[feature]: Make generating testReports files optional

### ISSUE THREAD

**Issue by tomtastico** [keploy/keploy#1393]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Right now, whenever a test run is finished, a `keploy/testReports/report-[number].yaml` file is generated with the test results.

In general these files are not really necessary for an end user, as we can see the test results in the console output. They should only be generated on request (by a CLI / config flag) in case the user needs to use them in some way.

### Why should this be worked on?

The `testReports` folder grows unchecked otherwise. I have to clean it manually now and then.

### Repository

keploy

**Comment by slayerjain** [comment]
@probablyArth Please try

**Comment by Akash-Singh04** [comment]
Hey there! @slayerjain , I have already been workimg on Two PR's related to adding CLI commands to keploy, which is why i feel like i should pick up this issue as i am already well versed with the required approach.

Here is my approach for the same:


We can add in a persistant flag to check if a command is run with --testreport flag inorder to check if the user wants these files to be generated

```
    rootCmd.PersistentFlags().BoolVar(&generateTestReportsFlag, "generate-test-reports", false, "Generate test reports")
```

We can then use this flag to check if the files are to be generated

Let me know if this approach works! Looking forward to getting started immediately!

**Comment by slayerjain** [comment]
anyone is free to open PR. we will merge the first PR that works well. 

@gouravkrosx please review this approach.

**Comment by gouravkrosx** [comment]
@Akash-Singh04 You can use normal flags so that the user can use the config file also to add this information.

**Comment by Akash-Singh04** [comment]
Great, working on this!

**Comment by Yaxhveer** [comment]
Is this issue still open?

**Comment by Akash-Singh04** [comment]
> Is this issue still open?

Hey there, Currently working on the final implementation for this!

**Comment by Akash-Singh04** [comment]
PR is ready for review! Awaiting feedback

**Comment by gouravkrosx** [comment]
@Akash-Singh04 In my opinion the default feature should generate the test reports and can be disabled using CLI/Config flag.

**Comment by Akash-Singh04** [comment]
Hey there, made a new PR with the new flag as per your request. Kindly look into it
