### ISSUE TITLE
[bug]: "failed to passthrough the mongo request to the actual database server" in test mode

### ISSUE THREAD

**Issue by tomups** [keploy/keploy#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running tests with `keploy test` with a NestJS (express) + MongoDB (via mongoose and native mongo driver), if the mongodb server is not running, I get

`failed to passthrough the mongo request to the actual database server` 

and the tests fail.

Maybe I'm not understanding how keploy works, but I thought that when testing, keploy would mock mongodb based on the requests that happened during recording, so mongodb would not need to be running?

If that's not the case then running the tests in CI as I was planning won't be possible as our mongodb server is not available from CI.

### Steps to reproduce

1. Record some tests with mongodb running, that make use of the DB
2. Stop mongodb
3. Run the tests

### Environment

Production

### Version

Self-hosted

### Repository

keploy

**Comment by slayerjain** [comment]
Hi @tomtastico thanks for reporting and your understanding is correct. Keploy mocks our mongo interactions so that you don't have to run mongo in your CI along with keploy tests. 

If keploy is not able to match a db call (generally when a new call happens which has not happened during record) keploy tries to pass through the call to the real mongo destination (as a fallback). 

In your case it could be a bug in the mongo parser. We have seen this issue internally and tracking it here - https://github.com/keploy/keploy/issues/1418

Once it is fixed we will test with a sample NestJS (express) + MongoDB app too. To ensure your issue is addressed quicker it would be great if you can create a sample app which recreates your problem for us to test against.

**Comment by gouravkrosx** [comment]
resolved by https://github.com/keploy/keploy/issues/1418, @tomups if your issue still persists, please feel free to reopen this issue.
