### ISSUE TITLE
[bug]: Blog website favicon are breaking

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Right now, currently when we navigate to the blog website the : https://keploy.io/blog we can see the keploy logo as favicon! But once we navigate to either 1. https://keploy.io/blog/community or 2. https://keploy.io/blog/technology . We can the logo missing, same is with for each blog post, favicon is missing.

 > both our blog directory and the individual blog articles are missing a favicon

### Steps to reproduce

1. go to https://keploy.io/blog/community

### Environment

Production

### Version

Cloud

### Repository

blog-website

**Comment by SubhashThenua** [comment]
Hi, @Sonichigo I want to work on this. Can you pls assign me?
Thanks!

**Comment by Aditya-eddy** [comment]
Hey @SubhashThenua are working on this issue?

**Comment by Aditya-eddy** [comment]
Hey @Sonichigo can please specify which img or favicons you are talking about. Because Keploy logo is present correctly on ->
https://keploy.io/blog and both the links (https://keploy.io/blog/technology && https://keploy.io/blog/community )
[
![Screenshot from 2024-02-07 21-30-56](https://github.com/keploy/keploy/assets/70089590/d92b650e-eeb2-4716-9fb9-675b2829d476)
![Screenshot from 2024-02-07 21-30-16](https://github.com/keploy/keploy/assets/70089590/1f54bae8-5819-4727-a775-a072ed1de2b5)
](url)

**Comment by Sonichigo** [comment]
<img width="822" alt="image" src="https://github.com/keploy/keploy/assets/53110238/bb9be90f-5dd8-4387-86fc-c50d5a8634cc">
My bad, forgot to mention! The favicon seems to show up only on chrome (webapp) and not in any other browser (including opera and edge) or on mobile devices.

**Comment by PiyushAryan** [comment]
Hey @Sonichigo @Aditya-eddy even on chrome Web browser on PC and Mobile it is not showing 

<img width="351" alt="image" src="https://github.com/keploy/keploy/assets/25245084/4103805b-c65a-4715-8422-a54f872d41c4">

**Comment by LalitDeore** [comment]
Hey @Sonichigo , I am working on this issue...
