### ISSUE TITLE
[bug]: Table of Contents Positioning Issue on Medium Screens

### ISSUE THREAD

**Issue by Hermione2408** [keploy/keploy#1771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Table of Contents does not remain 'sticky' to its designated area on medium-sized screens, potentially leading to layout inconsistencies
![Screenshot from 2024-04-02 13-31-14](https://github.com/keploy/keploy/assets/78696767/fdd01eef-1355-481c-901a-9b3cb2c2520e)

### Steps to reproduce

In the blog website resize the browser to a medium screen size or use a medium-sized device to access the page.

### Environment

None

### Version

Local

### Repository

blog-website

**Comment by its-kunal** [comment]
This layout inconsistency occurs due to wrong values used as breakpoints for large screens compared to tailwindcss.
Maybe [PR](https://github.com/keploy/blog-website/pull/41) will fix the issue.

Also, the table of contents overflows and looks inconsistent.

![image](https://github.com/keploy/keploy/assets/92196937/a36a1d83-7b30-4e78-9c5f-a9d30605ecbb)
