### ISSUE TITLE
[docs]:  wait, but you guys do not write any unit test?

### ISSUE THREAD

**Issue by xhd2015** [keploy/keploy#1794]
### What do you want to add to the docs? (please state reasons if any)

Didn't see any _test.go in the source code

### Where is this stated?

The repository

### Repository

keploy

**Comment by nehagup** [comment]
Hi @xhd2015, nice catch! that is on purpose - since we want to test keploy using keploy (like we did in v1). 

we just went through a major refactoring of the keploy code base with v2 and would achieve 75%+ coverage by testing keploy with keploy. 

Here is the PR - https://github.com/keploy/keploy/pull/1776

**Comment by xhd2015** [comment]
@nehagup Sounds crazy, however my interest arises... Thanks for your replying, I'll dig more.

**Comment by nehagup** [comment]
Hi @xhd2015 closing this issue for now, however, please feel free to re-open the issue if you may have any further questions. :)
