### ISSUE TITLE
[bug]: Web server for go.keploy.io appears to be down

### ISSUE THREAD

**Issue by embik** [keploy/keploy#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Not sure if this is the right place to report this, but we use a dependency that depends on keploy, and it appears that the domain hosting your go packages (`go.keploy.io`), or rather the web server behind it, is down/unavailable/misbehaving:

```sh
$ curl 'https://go.keploy.io/server?go-get=1' --max-time 60
curl: (28) Connection timed out after 60004 milliseconds
```

Modules cannot be downloaded anymore. I think this can potentially be fixed by a `rewrite` directive to point to GitHub instead, but I assume that's not the intention you had when using a dedicated domain for your module names instead of just `github.com/keploy/keploy`.

### Steps to reproduce

1. Run `curl 'https://go.keploy.io/server?go-get=1' --max-time 60` to connect to Go package domain or attempt to download dependencies for a Go project depending on e.g. `go.keploy.io/server`.

### Version

Local

**Comment by slayerjain** [comment]
Thanks, @embik for reporting the issue. We had a DNS issue with the keploy.io domain. Its resolved now, hope its working for you now.

**Comment by embik** [comment]
Looks good again @slayerjain, thank you for fixing it quickly!

**Comment by slayerjain** [comment]
Also to further prevent these kinds of issues we are now doing the following: 

1. The SDK uses the GitHub domain and not the keploy.io domain. The domain issues got unnecessarily propagated due to some shared libs. We will separate that into another repo - https://github.com/keploy/keploy/issues/213
2. Have separate modules for integration packages. These should ensure that their failures don't propagate in any way into keploy go-sdk's users.
