### ISSUE TITLE
[feature]: change mock file names after mock instead of tests

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#247]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently in test-export feature of keploy mocks are also generated if dependencies are wrapped by the user .
- So keploy's records testcases during `KEPLOY_MODE=record` and names each test in order they are created (_synchronously_) .
- for eg -  
<img width="243" alt="Screenshot 2022-12-08 at 12 45 17 PM" src="https://user-images.githubusercontent.com/50234097/206384578-ae7dae40-a4be-42d6-89e5-00c5a6ba0c0c.png">

- Since mapping between tests and mocks are done according to serial no. defined it would be nice to name mock names as same of tests. Hence change mock name from test-1.yaml to mock-1.yaml for example .

### Why should this be worked on?

It is required for better readability and understanding of keploy .

**Comment by DeepakKabdwal** [comment]
is someone working on this issue?

**Comment by nehagup** [comment]
@DeepakKabdwal this issue is not assigned yet!

**Comment by DeepakKabdwal** [comment]
Ok, thanks.
I want to contribute, can you explain what I have to do.

**Comment by re-Tick** [comment]
[Here](https://github.com/keploy/keploy/blob/d6fe7cfc7b8266c55ccda519876c40f75a4a9c57/pkg/service/testCase/testCase.go#L214), third parameter(test[0].Name) is the filename for mock yaml file. So, therefore you can write filename as "mock-<SEQ_NO>" instead of "test-<SEQ_NO>". 

  Currently, Keploy writes same filename for testcase and its mocks . In order to read testcase and their mocks from yaml file accordingly. Hence, [here](https://github.com/keploy/keploy/blob/d6fe7cfc7b8266c55ccda519876c40f75a4a9c57/pkg/platform/fs/mock.go#L157) currently, mocks are read from filename is "test-<SEQ_NO>". But now it should read from "mock-<SEQ_NO>" instead of "test-<SEQ_NO>".

**Comment by DeepakKabdwal** [comment]
> [Here](https://github.com/keploy/keploy/blob/d6fe7cfc7b8266c55ccda519876c40f75a4a9c57/pkg/service/testCase/testCase.go#L214), third parameter(test[0].Name) is the filename for mock yaml file. So, therefore you can write filename as "mock-<SEQ_NO>" instead of "test-<SEQ_NO>".
> 
> Currently, Keploy writes same filename for testcase and its mocks . In order to read testcase and their mocks from yaml file accordingly. Hence, [here](https://github.com/keploy/keploy/blob/d6fe7cfc7b8266c55ccda519876c40f75a4a9c57/pkg/platform/fs/mock.go#L157) currently, mocks are read from filename is "test-<SEQ_NO>". But now it should read from "mock-<SEQ_NO>" instead of "test-<SEQ_NO>".

Hey,
I can not find the LOC where the mocks are being read can you check that please.

**Comment by re-Tick** [comment]
Hi @DeepakKabdwal,  the mocks are read and returned by [this](https://github.com/keploy/keploy/blob/d6fe7cfc7b8266c55ccda519876c40f75a4a9c57/pkg/platform/fs/mock.go#L157) function call. So here we just have to change the name to mock-<SEQ_NO> from test-<SEQ_NO>.

**Comment by PranshuSrivastava** [comment]
I would like to work on this issue

**Comment by Sarthak160** [comment]
> I would like to work on this issue

Cool 😄
