### ISSUE TITLE
[feat]: Increase test coverage of Keploy Server using Keploy

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#333]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

This task is to increase the test coverage of the keploy server by capturing more test cases and mocks after running keploy locally. The idea is to test keploy with keploy. Currently, the test coverage is 75% which can be seen in the readme represented with the coveralls badge. 

### Why should this be worked on?

To improve the quality of code and reduce the risk of breaking changes impacting users.

**Comment by aagrawal7** [comment]
hey, I want to work on this.

**Comment by SanskritiHarmukh** [comment]
Hi @aagrawal7 , since this is a gsoc issue, it will not be assigned to anyone rather you can start working on it directly and raise a PR for the same. After creating a PR, wait for a review from us and as soon as we add `Don't Merge` and `Accepted` label to your PR, add the PR ID to the task table under [the CLI Refactoring project ](https://github.com/keploy/gsoc/tree/main/2023#1-keploy-cli-refactoring) corresponding to the issue.
