### ISSUE TITLE
[feature]: Add support for Get TC to display test-cases from yaml	

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#337]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

1. Since `test-export` feature Keploy fetches all the testcases from the user's provided code path and runs complete test run.
2. It will be good to be add a support for getting a testcase with a given `testID` from the yamls .
3. Currently GetTC method of the keploy server is only available for database export .
4. The core method for implementing this is inside the `grpc/grpcserver` module .

### Why should this be worked on?

1. This should be worked on to get an testcase through id and can be added this feature to display on CLI .
2. It will make easier to handle different tests as user can visualize only testcase that have to be debugged .

**Comment by shreyanshshah27** [comment]
Hey @Sarthak160 I would like to work on this. It would be great if you can assign this to me.

**Comment by nehagup** [comment]
Hey @shreyanshshah27 since this is a gsoc issue, it will not be assigned to anyone rather you can start working on it directly and raise a PR for the same. After creating a PR, add the PR ID to the task table under [the CLI Refactoring project](https://github.com/keploy/gsoc/tree/main/2023#1-keploy-cli-refactoring) corresponding to the issue.

**Comment by Sarthak160** [comment]
This issue can be updated with the keploy V2 CLI command , May be we need this feature in future but as of now , User is considered to record tescases with different record sessions.
