### ISSUE TITLE
[bug]: Race conditions while running multiple tests in parallel

### ISSUE THREAD

**Issue by aerowisca** [keploy/keploy#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While creating the tests for the application, we run all tests in parallel, with a semaphore of size 10. However, if any of the tests fail, we return a fail verdict to the caller via the `passed` boolean variable to the `result` channel. However, this variable is being shared by 10 goroutines at the same time, which can cause race conditions, depending upon the API time of those endpoints.

### Steps to reproduce

Since this is a race condition, it's pretty difficult to simulate in local environment. However, please take a look at the [update phase](https://github.com/keploy/go-sdk/blob/ec714e1d8fb92aa80bff0a88d1096de352541043/keploy/keploy.go#L323) and the [concurrent execution](https://github.com/keploy/go-sdk/blob/ec714e1d8fb92aa80bff0a88d1096de352541043/keploy/keploy.go#L320)

### Environment

None

### Version

Cloud

**Comment by slayerjain** [comment]
@aerowisca Thanks for reporting this. Yes this could probably cause a race condition since we are updating the variable. Good find! 

@re-Tick is working on moving most of the testing logic to the keploy binary, since its currently being duplicated across all SDKs. 

@re-Tick Please ensure we handle this race condition in that implementation and close this issue.

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
