### ISSUE TITLE
[bug]: unexpected behaviour when clicking on golang collapser in v1.0.0 docs for explanation

### ISSUE THREAD

**Issue by AkashKumar7902** [keploy/keploy#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Clicking on golang collapser opens up the page linked with "Sample Quickstarts" collapser.
![image](https://github.com/keploy/keploy/assets/91385321/f6ccfdd5-d4d1-4c8f-bfa5-1297a4af2aed)

A desired behaviour of golang collapser should be to collapse or expand.

### Steps to reproduce

1. Go to https://docs.keploy.io/docs/1.0.0/keploy-explained/introduction/
2. click on golang from the sidebar.

### Environment

None

### Version

Cloud

### Repository

docs

**Comment by nehagup** [comment]
@AkashKumar7902 this is expected behaviour. There's a page hosted on Golang collapser that prodvides summary of the Golang section. It may require more info around installation and integration in Go page links, however, summary on Golang collapser is expected. 

p.s. - you are exploring docs for keploy v1.0.0 which is now deprecated. :)
