### ISSUE TITLE
[sample-apps]: add a new samples app using java & dynamodb

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#912]
- Create a Simple CRUD application using Java and DynamoDB.
- Use the Keploy to test the app and create at least 3 testcases.
- Create a Readme containing the method to run the application with Keploy using Docker and Natively
- Make a PR to [Keploy/Samples-java](https://github.com/keploy/samples-java) repository

**Comment by sagar-7227** [comment]
Hey, @Sonichigo I would like to work on this issue. 
Can you assign it to me?

**Comment by nehagup** [comment]
@sagar-7227 sure you can take this!

**Comment by sagar-7227** [comment]
@nehagup Thanks!

**Comment by Sonichigo** [comment]
Hey @sagar-7227 are you working on this? Can you share progress if yes?

**Comment by sagar-7227** [comment]
Hey @Sonichigo although the app tested properly without dynamodb, when try to hit the endpoint with dynamo through keploy it gives several certs errors.

2023-10-02T14:36:02.176+05:30 ERROR 38380 --- [nio-9090-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: com.amazonaws.SdkClientException: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] with root cause
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by CypherpunkSamurai** [comment]
Hello 👋🏻 is this issue active? I want to contribute to and thought this would be a good issue

**Comment by nehagup** [comment]
@CypherpunkSamurai please feel free to add a PR. this is open for all

**Comment by Sonichigo** [comment]
Closing this stale issue.
